ads/urls.py
from django.urls import path
from config import settings
from django.conf.urls.static import static

from ads.apps import AdsConfig
from ads.views import ads_filter, ads_lst_with_create, create_ads_confirm, create_proposal_confirm, custom_warning, delete_ads_confirm, delete_prop_confirm, proposals_lst_with_create, update_ads_confirm, update_prop_confirm, warning_ads_not_exits

app_name = AdsConfig.name

urlpatterns = [
    
    path('', ads_lst_with_create, name='ads_lst'),
    path('ads_filter', ads_filter, name='ads_filter'),
    path('create_ads_confirm/<int:pk>', create_ads_confirm, name='create_ads_confirm'),
    path('update_ads_/<int:pk>', update_ads_confirm, name='update_ads_confirm'),
    path('delete_ads/<int:pk>', delete_ads_confirm, name='delete_ads_confirm'),
    path('custom_warning/', custom_warning, name='custom_warning'),
    path('warning_ads_not_exits/', warning_ads_not_exits, name='warning_ads_not_exits'),
    
    path('proposals_lst_with_create', proposals_lst_with_create, name='proposals_lst_with_create'),
    path('create_proposal_confirm/<int:pk>', create_proposal_confirm, name='create_proposal_confirm'),
    path('update_prop_confirm/<int:pk>', update_prop_confirm, name='update_prop_confirm'),
    path('delete_prop_confirm/<int:pk>', delete_prop_confirm, name='delete_prop_confirm'),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import include, path
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('ads/', include('ads.urls', namespace='ads')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe

NULLABLE = {'blank': True, 'null': True}


STATUSES = [('STATUS_NEW', 'new'), ('STATUS_USED', 'used'),]

"""Модель - Объявленеие"""
class Advertisement(models.Model):
    
    category = models.CharField( max_length=150, verbose_name=_("Ads's category"))
    user = models.ForeignKey("users.CustomUser", related_name="user", on_delete=models.CASCADE)
    title = models.CharField(max_length=150, verbose_name=_("Ads's title"))
    description = models.CharField(max_length=2000, verbose_name=_("Description"))
    image = models.ImageField(upload_to='media', **NULLABLE)
    created = models.DateTimeField(auto_now_add = True)
    status = models.CharField(choices=STATUSES, default='STATUS_USED')

    @property
    def image_url(self):
        if self.image :
            return self.image.url
        return ''

    def __str__(self):
        return str(self.user)
    

statut = [("waiting","waiting"), ("accepted","accepted"), ("rejected", "rejected"),]

"""Модель - Предложение"""
class ExchangeProposal(models.Model):
    user = models.ForeignKey('users.CustomUser', on_delete=models.CASCADE, \
                                  related_name='customuser', verbose_name="Номер инициатора предложения")
    ad_sender = models.ForeignKey('ads.Advertisement', on_delete=models.CASCADE, \
                                  related_name='sender', verbose_name="Номер объявления инициатора предложения")
    ad_receiver = models.ForeignKey('ads.Advertisement', on_delete=models.CASCADE,\
                                     related_name='receiver', verbose_name="Номер объявления принимающего предложения")
    comment = models.CharField(max_length=350 , verbose_name="Комментраий")
    status = models.CharField(choices=statut, default="waiting")
    created_at =  models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return str(self.id)

ads/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse

from ads.form import CreateAdsForm, CreateProposalsForm, DeleteAdsForm, FilterAdsForm, UpdateAdsForm, UpdatePropForm
from ads.models import Advertisement, ExchangeProposal
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from users.models import CustomUser


"""Список объявлений. Форма создания сверху"""
def ads_lst_with_create(request):
    if request.user.is_anonymous:
        return redirect('users:log_in')
        
    ads_queryset = Advertisement.objects.all()
    form = CreateAdsForm(request.POST, request.FILES)
    if request.method == 'POST':
        if form.is_valid():
            ads_instance = Advertisement(user=CustomUser.objects.get(id=request.user.id), **form.cleaned_data)
            ads_instance.save()
            return redirect(reverse('ads:create_ads_confirm', kwargs={'pk':ads_instance.id}))
    else:
        form = CreateAdsForm()

    context = {'form': form,
               'ads_queryset':ads_queryset,
               'user': request.user}
    return render(request, 'ads/templates/ads_lst.html', context)


"""Подтверждение создания объявления"""
def create_ads_confirm(request, **kwargs):
    pk=kwargs['pk']
    context ={}
    try:
        new_ads_obj = Advertisement.objects.get(id=pk)
        context = {'new_ads_obj':new_ads_obj,
                   "user":request.user}
    except:
        Advertisement.DoesNotExist
        return redirect('ads:ads_lst')
        
    return render(request, 'ads/templates/create_ads_confirm.html', context)


"""Редактирование объявления"""
def update_ads_confirm(request, pk):
    if request.user.is_anonymous:
        return redirect('users:log_in')
    
    instance = Advertisement.objects.get(id=pk)
    context = {"form": UpdateAdsForm(initial={"id":instance.id, "title": instance.title, "image": instance.image,\
                    "category":instance.category, "description": instance.description}),"ads": instance, }
    
    if request.method == "GET":
        return render(request,"ads/templates/update_ads.html",context)
    
    elif request.method == "POST":
        if not instance.user==request.user:
            return HttpResponseRedirect(reverse('ads:custom_warning'))
        form = UpdateAdsForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse('ads:create_ads_confirm', kwargs={'pk':form.instance.id}))
    return render(request, 'ads/templates/update_ads.html', context)


"""Ендпоинт - Предупреждение, если нет права."""
def custom_warning(request, **kwargs):
    context = {}
    return render(request, 'ads/templates/custom_warning.html', context)


"""Ендпоинт - Предупреждение, если нет объекта."""   
def warning_ads_not_exits(request, **kwargs):
    context = {}
    return render(request, 'ads/templates/warning_ads_not_exits.html', context)


"""Удаление объявления"""
def delete_ads_confirm(request, pk):
    if request.user.is_anonymous:
        return redirect('users:log_in')
    try:
        instance = Advertisement.objects.get(id=pk)
    except Advertisement.DoesNotExist:
        return redirect('ads:warning_ads_not_exits')
    if request.method == 'POST':
        if not instance.user==request.user:
            return HttpResponseRedirect(reverse('ads:custom_warning'))
        form = DeleteAdsForm(request.POST, instance=instance)
        if form.is_valid():
            instance.delete()
            return HttpResponseRedirect(reverse("ads:ads_lst"))
    else:
        form = DeleteAdsForm(instance=instance)
    context ={"form":form}
    return render(request, 'ads/templates/delete_ads.html', context)


"""Фильтрация по категории и состоянию товара. Фильтруем и по айди. Пагинация, \
    без которой все фильтрация работает и с которой наоборот, не работатет."""
def ads_filter(request):
    
    if request.user.is_anonymous:
        return redirect('users:log_in')
    form = FilterAdsForm(request.POST, request.FILES)
    ads_queryset = Advertisement.objects.all()
    p = Paginator(ads_queryset, 5)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number) 
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)
   

    if form.is_valid():
        min_id_value = form.cleaned_data['min_id']
        max_id_value = form.cleaned_data['max_id']
        category_for_search_value = form.cleaned_data['category_for_search']
        status_for_search_value = form.cleaned_data['status_for_search']
        if form.cleaned_data['min_id']:
                    ads_queryset=ads_queryset.filter(id__gte=min_id_value)
        if form.cleaned_data['max_id']:
            ads_queryset=ads_queryset.filter(id__lte=max_id_value)
            
        if form.cleaned_data['category_for_search']:
            ads_queryset=ads_queryset.filter(category=category_for_search_value)
        if form.cleaned_data['status_for_search']:
            ads_queryset=ads_queryset.filter(status=status_for_search_value)
        if form.cleaned_data['category_for_search'] and form.cleaned_data['status_for_search'] and form.cleaned_data['max_id']\
              and form.cleaned_data['min_id']:
            ads_queryset=ads_queryset.filter(id__gte=min_id_value).filter(id__lte=max_id_value).\
                filter(category=category_for_search_value).filter(status=status_for_search_value)
        if form.cleaned_data['category_for_search'] and form.cleaned_data['max_id'] :
            ads_queryset=ads_queryset.filter(id__lte=max_id_value).filter(category=category_for_search_value)
        if form.cleaned_data['category_for_search'] and form.cleaned_data['min_id']:
            ads_queryset=ads_queryset.filter(id__gte=min_id_value).filter(category=category_for_search_value)
        if form.cleaned_data['status_for_search'] and form.cleaned_data['max_id'] :
            ads_queryset=ads_queryset.filter(id__lte=max_id_value).filter(status=status_for_search_value)
        if form.cleaned_data['status_for_search'] and form.cleaned_data['min_id']:
            ads_queryset=ads_queryset.filter(id__gte=min_id_value).filter(status=status_for_search_value)
        context = {'form': form,
               'ads_queryset':ads_queryset,
               'page_obj': page_obj}
        
    return render(request, 'ads/templates/ads_filtere_lst.html', context)


"""Список Предложений. Форма создания сверху"""
def proposals_lst_with_create(request):
    if request.user.is_anonymous:
        return redirect('users:log_in')
      
    prop_queryset = ExchangeProposal.objects.all()
    form = CreateProposalsForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            print('7777777777777777777777777777777', type(form.cleaned_data['ad_sender'][0]))
            prop_instance = ExchangeProposal(user=CustomUser.objects.get(id=request.user.id),\
                    ad_sender=form.cleaned_data['ad_sender'][0], ad_receiver=form.cleaned_data['ad_receiver'][0],\
                    comment=form.cleaned_data['comment'], status=form.cleaned_data['status'])

            # prop_instance = form.save(commit=False)
            # prop_instance = ExchangeProposal(user=CustomUser.objects.get(id=request.user.id), **form.cleaned_data)
            prop_instance.save()
            # form.save()
            return redirect(reverse('ads:create_proposal_confirm', kwargs={'pk':prop_instance.id}))
    else:
        form = CreateProposalsForm()

    context = {'form': form,
               'prop_queryset':prop_queryset,
               'user':request.user}
    return render(request, 'ads/templates/proposals_lst_with_create.html', context)


"""Подтверждение создания предложения"""
def create_proposal_confirm(request, **kwargs):
    pk=kwargs['pk']
    context ={}
    try:
        new_prop_obj = ExchangeProposal.objects.get(id=pk)
        context = {'new_prop_obj':new_prop_obj,
                   "user":request.user}
    except:
        ExchangeProposal.DoesNotExist
        return redirect('ads:proposals_lst_with_create')
        
    return render(request, 'ads/templates/create_prop_confirm.html', context)


"""Редактирование предложения"""
def update_prop_confirm(request, pk):
    instance = ExchangeProposal.objects.get(id=pk)
    context = {"form": UpdatePropForm(initial={"id":instance.id, "ad_sender": instance.ad_sender, "ad_receiver": instance.ad_receiver,\
                    "comment":instance.comment, "status": instance.status}),"prop": instance, }
    
    if request.method == "GET":
        return render(request,"ads/templates/update_ads.html",context)
    
    elif request.method == "POST":
        if not instance.ad_sender==request.user:
            return HttpResponseRedirect(reverse('ads:custom_warning'))
        form = UpdatePropForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            prop_instance = form.save(commit=False)
            prop_instance.status = form.cleaned_data['status']
            prop_instance.save()
            # form.save()
            return redirect(reverse('ads:create_proposal_confirm', kwargs={'pk':form.instance.id}))
    return render(request, 'ads/templates/update_prop.html', context)


"""Удаление объявления"""
def delete_prop_confirm(request, pk):
    try:
        instance = ExchangeProposal.objects.get(id=pk)
    except ExchangeProposal.DoesNotExist:
        return redirect('ads:warning_ads_not_exits')
    if request.method == 'POST':
        if not instance.ad_sender==request.user:
            return HttpResponseRedirect(reverse('ads:custom_warning'))
        form = DeleteAdsForm(request.POST, instance=instance)
        if form.is_valid():
            instance.delete()
            return HttpResponseRedirect(reverse("ads:proposals_lst_with_create"))
    else:
        form = DeleteAdsForm(instance=instance)

ads/templates/ads_filtere_lst.html
  {% include 'templates/main_menu.html' %}
 <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="submit" value="Поиск">
</form>

 <table class="table table-dark table-striped">
          <thead>
            <tr>
                <th scope="col">Ads title</th>
                <th scope="col">Ads id</th>
                <th scope="col">Ads created by user </th>
                 <th scope="col">Condition</th>
                <th scope="col">Category</th>
                <th scope="col">Image</th>
                <th scope="col">Make choice</th>

            </tr>
          </thead>
<tbody>
     {%if ads_queryset%}
    {%for item in page_obj.object_list%}
     <tr>
                    <td>{{item.title}}</td>
                    <td> {{item.id}} </td>
                    <td> {{item.user}} </td>
                    <td> {{item.status}} </td>
                    <td> {{item.category}} </td>
                    <td>
                        {%if item.image%}
                        <div class = "profile-pic-wrapper">
                            <img src="{{item.image.url}}"  alt="" class="rounded-circle" data-bs-target="#exampleModal", height="50"/>
                        </div> 
                        {%endif%}
                    </td>
                     <td>
                        <a class="btn.btn-default" href="{% url 'ads:update_ads_confirm' item.pk %}" >Update</a>
                        <a class="btn.btn-default" href="{% url 'ads:ads_lst'  %}" >Create</a>
                        <a class="btn.btn-default" href="{% url 'ads:delete_ads_confirm' item.pk %}" >Delete</a>

                    </td>


           
                </tr>
{%endfor%}
    {%endif%}
    <center>
        {%if page_obj.has_previous %} {# whether the previous page exists #}
            <a href="?page={{page_obj.previous_page_number}}"><</a> {# link to the prev page #}
        {% endif %}
        <span>{{page_obj.number}}</span> {# the current page number #}
      
        {%if page_obj.has_next %} {# whether the next page exists #}
            <a href="?page={{page_obj.next_page_number}}">></a> {# link to the next page #}
        {% endif %}
    </center>
</tbody>
</table>


    

ads/templates/ads_lst.html
 {% include 'templates/main_menu.html' %}
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Создание книги</title>
</head>
<body>
    <h1>Создать объявление</h1>
    <form method="post" enctype = "multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>

   
    <table class="table table-dark table-striped">
          <thead>
            <tr>
                <th scope="col">Ads title</th>
                <th scope="col">Ads id</th>
                <th scope="col">Ads created by user </th>
                 <th scope="col">Condition</th>
                <th scope="col">Category</th>
                <th scope="col">Image</th>
                <th scope="col">Make choice</th>

            </tr>
          </thead>
<tbody>
     {%if ads_queryset%}
    {%for item in ads_queryset%}
     <tr>
                    <td>{{item.title}}</td>
                    <td> {{item.id}} </td>
                    <td> {{item.user}} </td>
                    <td> {{item.status}} </td>
                    <td> {{item.category}} </td>
                    <td>
                        {%if item.image%}
                        <div class = "profile-pic-wrapper">
                            <img src="{{item.image.url}}"  alt="" class="rounded-circle" data-bs-target="#exampleModal", height="50"/>
                        </div> 
                        {%endif%}
                    </td>
                     <td>
                        <a class="btn.btn-default" href="{% url 'ads:update_ads_confirm' item.pk %}" >Update</a>
                        <a class="btn.btn-default" href="{% url 'ads:ads_lst'  %}" >Create</a>
                        <a class="btn.btn-default" href="{% url 'ads:delete_ads_confirm' item.pk %}" >Delete</a>

                    </td>


           
                </tr>
{%endfor%}
    {%endif%}

</tbody>
</table>
    
  Активный пользователь {{user}}
</html>

ads/templates/create_ads_confirm.html
 {% include 'templates/main_menu.html' %}
 Активный пользователь {{user}}
  <h4>
    Создано объявление со следующими параметрами
 </h4>
<p>
   Номер {{new_ads_obj.id}} 
</p>
<p>
    Название {{new_ads_obj.title}}
</p>
<p>
    Создано {{new_ads_obj.create}}
</p>
<p>
    Категория {{new_ads_obj.category}}
</p>
<p>
    Картинка {{new_ads_obj.image}}
</p>
<p>
    Описание {{new_ads_obj.description}}
</p>
<p>
    Пользователя  {{new_ads_obj.user}}
</p>

ads/templates/create_prop_confirm.html
 {% include 'templates/main_menu.html' %}
 Активный пользователь {{user}}
  <h4>
    Создано предложение со следующими параметрами
 </h4>
<p>
   Номер {{new_prop_obj.id}} 
</p>
<p>
    Предлагающий предложение  {{new_prop_obj.ad_sender}}
</p>
<p>
    Принимающий предложение  {{new_prop_obj.ad_receiver}}
</p>
<p>
    Комментарий {{new_prop_obj.comment}}
</p>
<p>
    Статус {{new_prop_obj.status}}
</p>

<p>
    Создано  {{new_prop_obj.created_at}}
</p>

ads/templates/custom_warning.html
{% include 'templates/main_menu.html' %}

<h3>
    Вы не имеете права на совершение этих действий. Выберете в верху вариант в меню
</h3>

ads/templates/delete_ads.html
<h3>Удаляем объявление</h3>

<form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{form.as_p}}

                  <button class="btn btn-outline-secondary" type="submit" id="input-group-text">Button</button>

            </form>

ads/templates/delete_prop.html
<h3>Удаляем предложение</h3>

<form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{form.as_p}}

                  <button class="btn btn-outline-secondary" type="submit" id="input-group-text">Button</button>

            </form>

ads/templates/proposals_lst_with_create.html
 {% include 'templates/main_menu.html' %}
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    </head>
<body>
    <h1>Создать предлоржение</h1>
    <form method="post" enctype = "multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>

    <table class="table table-dark table-striped">
          <thead>
            <tr>
                <th scope="col">Proposal id</th>
                <th scope="col">Proposal created </th>
                <th scope="col">Proposal sender</th>
                <th scope="col">Proposal receiver</th>
                <th scope="col">Proposal comment</th>
                <th scope="col">Status</th>
                <th scope="col">Make choice</th>

            </tr>
          </thead>
<tbody>
     {%if prop_queryset%}
    {%for item in prop_queryset%}
     <tr>
                    <td> {{item.id}} </td>
                    <td>{{item.created}}</td>
                    <td> {{item.sender}} </td>
                    <td> {{item.receiver}} </td>
                    <td> {{item.comment}} </td>
                    <td> {{item.status}} </td>
                     <td>
                        <a class="btn.btn-default" href="{% url 'ads:update_prop_confirm' item.pk %}" >Update</a>
                        <a class="btn.btn-default" href="{% url 'ads:proposals_lst_with_create'  %}" >Create</a>
                        <a class="btn.btn-default" href="{% url 'ads:delete_prop_confirm' item.pk %}" >Delete</a>

                    </td>


           
                </tr>
{%endfor%}
    {%endif%}

</tbody>
</table>
    
 Активный пользователь  {{user}}
 
</html>

ads/templates/update_ads.html
 <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{form.as_p}}

                  <button class="btn btn-outline-secondary" type="submit" id="input-group-text">Button</button>

            </form>

ads/templates/update_prop.html
 <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{form.as_p}}

                  <button class="btn btn-outline-secondary" type="submit" id="input-group-text">Button</button>

            </form>
Instance {{prop}}

ads/templates/warning_ads_not_exits.html
{% include 'templates/main_menu.html' %}

<h3>
    Такого объявления не существует
</h3>