ads/urls.py
from django.urls import path
from config import settings
from django.conf.urls.static import static

from ads.apps import AdsConfig
from ads.views import ads_filter, ads_lst_with_create, create_ads_confirm, create_proposal_confirm, custom_warning, delete_ads_confirm, delete_prop_confirm, proposals_lst_with_create, update_ads_confirm, update_prop_confirm, warning_ads_not_exits

app_name = AdsConfig.name

urlpatterns = [
    
    path('', ads_lst_with_create, name='ads_lst'),
    path('ads_filter', ads_filter, name='ads_filter'),
    path('create_ads_confirm/<int:pk>', create_ads_confirm, name='create_ads_confirm'),
    path('update_ads_/<int:pk>', update_ads_confirm, name='update_ads_confirm'),
    path('delete_ads/<int:pk>', delete_ads_confirm, name='delete_ads_confirm'),
    path('custom_warning/', custom_warning, name='custom_warning'),
    path('warning_ads_not_exits/', warning_ads_not_exits, name='warning_ads_not_exits'),
    
    path('proposals_lst_with_create', proposals_lst_with_create, name='proposals_lst_with_create'),
    path('create_proposal_confirm/<int:pk>', create_proposal_confirm, name='create_proposal_confirm'),
    path('update_prop_confirm/<int:pk>', update_prop_confirm, name='update_prop_confirm'),
    path('delete_prop_confirm/<int:pk>', delete_prop_confirm, name='delete_prop_confirm'),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import include, path
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('ads/', include('ads.urls', namespace='ads')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
                                                                 
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from users.apps import UsersConfig
from users.views import log_out, log_in, my_registration, users_lst
app_name = UsersConfig.name

urlpatterns = [

    path('', log_in, name='log_in'),
        #   CustomLoginView.as_view(template_name='registration/login.html')
    path('log_out', log_out, name='log_out'),
    path('my_registration', my_registration, name='my_registration'),
    path('users_lst', users_lst, name='users_lst'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Signin Template · Bootstrap v5.3</title>

    <link href="{% static 'style1.css' %}" rel="stylesheet">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sign-in/">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.4/components/flag.css">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        html,
        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            max-width: 330px;
            padding: 15px;
        }

        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
        body {
     background: #FFF;
     color: #000;
     font-family: Arial, sans-serif;
     font-size: 14px;
}
        
    </style>

</head>
<body class="text-center">

<main class="form-signin w-100 m-auto">
    <h1>worktime</h1>
    {% block content %}
    {% endblock %}

</main>


</body>
</html>

templates/main_menu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"> </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'users:log_in' %}"> Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:log_out' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ads:ads_lst' %}">Ads lst with create</a>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'ads:ads_filter' %}">Ads lst filtered</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'ads:proposals_lst_with_create' %}">Proposals lst </a>
        </li>
       
       
        </li>
      </ul>
    </div>
  </div>
</nav>